// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBniIsWNg42ZqzpR-rctke-B75M9n4bFdU',
    appId: '1:21624455168:web:41cb8f4ce40514aaec58e5',
    messagingSenderId: '21624455168',
    projectId: 'bingo-game-3e70f',
    authDomain: 'bingo-game-3e70f.firebaseapp.com',
    storageBucket: 'bingo-game-3e70f.firebasestorage.app',
    measurementId: 'G-XZ0N2NJKX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0YmtxhD499ST41oUj5_xi0BhSdVrbKx8',
    appId: '1:21624455168:android:15f8d3baddffb4d4ec58e5',
    messagingSenderId: '21624455168',
    projectId: 'bingo-game-3e70f',
    storageBucket: 'bingo-game-3e70f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqP2WETjbzYs6U2pdtkPv2-kOz97bu0Yg',
    appId: '1:21624455168:ios:ae9d24ac392fd8eeec58e5',
    messagingSenderId: '21624455168',
    projectId: 'bingo-game-3e70f',
    storageBucket: 'bingo-game-3e70f.firebasestorage.app',
    iosBundleId: 'com.example.bingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqP2WETjbzYs6U2pdtkPv2-kOz97bu0Yg',
    appId: '1:21624455168:ios:ae9d24ac392fd8eeec58e5',
    messagingSenderId: '21624455168',
    projectId: 'bingo-game-3e70f',
    storageBucket: 'bingo-game-3e70f.firebasestorage.app',
    iosBundleId: 'com.example.bingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBniIsWNg42ZqzpR-rctke-B75M9n4bFdU',
    appId: '1:21624455168:web:78ef0830cb5377a9ec58e5',
    messagingSenderId: '21624455168',
    projectId: 'bingo-game-3e70f',
    authDomain: 'bingo-game-3e70f.firebaseapp.com',
    storageBucket: 'bingo-game-3e70f.firebasestorage.app',
    measurementId: 'G-QJJY1WKTN8',
  );
}
